name: Deploy Documentation

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy-docs:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: "Install AutoEIS"
        run: |
            python -m pip install --upgrade pip
            pip install -e .[doc]
            # Install Julia dependencies at first import
            python -c "import autoeis"            

      # Build the documentation
      - name: Build the documentation
        run: |
          cd doc
          make html

      # Push the documentation's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html
