name: Tests

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        julia-version: ['1.10']
        python-version: ['3.10']
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia
        uses: julia-actions/cache@v1
        with:
          cache-name: ${{ matrix.os }}-test-${{ matrix.julia-version }}-${{ matrix.python-version }}
          cache-packages: false

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with: 
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}          

      - name: Install AutoEIS
        run: |
            uv sync --dev
            # Install Julia dependencies at first import
            uv run python -c "import autoeis"

      - name: Run tests
        run: |
          uv run pytest -v tests/
